language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export TZ=America/New_York
- date
script: mvn clean org.codehaus.mojo:versions-maven-plugin:2.2:set -DnewVersion=${TRAVIS_COMMIT::7} -DprocessParent=true package
after_script: ls target
notifications:
  email: false
deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file: target/herman-bamboo-plugin-${TRAVIS_COMMIT::7}.jar
  skip_cleanup: true
  on:
    repo: libertymutual/herman
    tags: true
