language: java
jdk: oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_install:
  - export TZ=America/New_York
  - date
  - export BUILD_VERSION="1.0.$TRAVIS_BUILD_NUMBER"
  - mvn org.codehaus.mojo:versions-maven-plugin:2.2:set -DnewVersion=$BUILD_VERSION

after_script:
  - ls target
  - git tag $BUILD_VERSION

notifications:
  email: false

deploy:
  provider: releases
  api_key: $GH_DEPLOY_TOKEN
  file: target/herman-bamboo-plugin-$BUILD_VERSION.jar
  skip_cleanup: true
  on:
    repo: libertymutual/herman
    tags: true
